[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT ml-api-server:app --workers 1 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
